# Generated by Django 5.1.5 on 2025-02-04 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Unnamed Booking', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_slot',
            field=models.IntegerField(),
        ),
    ]
